Add missing fmt lib file
Ran into a couple issues without it for the armory networking such as /usr/bin/ld: kore_sources.o: in function `haxe_crypto_Sha1_make':
kore_sources.c:(.text+0x49ea4): undefined reference to `fmt_digest'